update

diff --git a/.github/workflows/deploy-to-ec2.yml b/.github/workflows/deploy-to-ec2.yml
--- a/.github/workflows/deploy-to-ec2.yml
+++ b/.github/workflows/deploy-to-ec2.yml
@@ -7,35 +7,54 @@ on:
       - master
 
 jobs:
-  deploy:
-    name: Deploy to EC2 on master branch push
+  build:
     runs-on: ubuntu-latest
 
     steps:
-      - name: Checkout code
+      - name: Checkout repository
         uses: actions/checkout@v2
 
-      - name: Deploy to Server
-        uses: easingthemes/ssh-deploy@main
-        env:
-          SSH_PRIVATE_KEY: ${{ secrets.EC2_SSH_KEY }}
-          REMOTE_HOST: ${{ secrets.HOST_DNS }}
-          REMOTE_USER: ${{ secrets.USERNAME }}
-          TARGET: ${{ secrets.TARGET_DIR }}
-      
-      - name: Update RDS secrets on EC2
-        uses: appleboy/ssh-action@master
-        with:
-          host: ${{ secrets.HOST_DNS }}
-          username: ${{ secrets.USERNAME }}
-          key: ${{ secrets.EC2_SSH_KEY }}
-          script: |
-            echo "export RDS_USERNAME=${{ secrets.RDS_USERNAME }}" | sudo tee -a /etc/apache2/envvars
-            echo "export RDS_PASSWORD=${{ secrets.RDS_PASSWORD }}" | sudo tee -a /etc/apache2/envvars
-            echo "export RDS_ENDPOINT=${{ secrets.RDS_ENDPOINT }}" | sudo tee -a /etc/apache2/envvars
-            echo "export RDS_DATABASE=${{ secrets.RDS_DATABASE }}" | sudo tee -a /etc/apache2/envvars
+      - name: Set up Docker Buildx
+        uses: docker/setup-buildx-action@master
+        
+      - name: Login to Docker Hub
+        run: echo ${{ secrets.DOCKERHUB_TOKEN }} | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin
 
+      - name: Build and push Docker image
+        run: |
+          docker buildx create --use
+          docker buildx inspect --bootstrap
+          docker buildx build --load -t my-doc-app:latest .
+          docker tag my-doc-app:latest ${{ secrets.DOCKERHUB_USERNAME }}/fexam:latest
+          echo $(docker images)
+          docker push ${{ secrets.DOCKERHUB_USERNAME }}/fexam:latest
 
+      - name: Check Docker Image Build
+        run: |
+          if docker inspect my-doc-app:latest &> /dev/null; then
+            echo "Docker image built successfully. Test passed!"
+          else
+            echo "Docker image not found. Test failed."
+            exit 1
+          fi
+
+      - name: Check Docker Image Pushed
+        run: |
+          if docker manifest inspect ${{ secrets.DOCKERHUB_USERNAME }}/fexam:latest &> /dev/null; then
+            echo "Docker image pushed to Docker Hub successfully. Test passed!"
+          else
+            echo "Docker image not found on Docker Hub. Test failed."
+            exit 1
+          fi
+
+      - name: Logout from Docker Hub
+        run: docker logout
+
+  deploy:
+    needs: build
+    runs-on: ubuntu-latest
+
+    steps:
       - name: Executing remote ssh commands using ssh key
         uses: appleboy/ssh-action@master
         with:
@@ -43,9 +62,13 @@ jobs:
           username: ${{ secrets.USERNAME }}
           key: ${{ secrets.EC2_SSH_KEY }}
           script: |
-            if [ -f /var/www/html/index.html ]; then
-            sudo rm -rf /var/www/html/index.html
+            existing_container=$(docker ps -q -f name=my-doc-app)
+            if [ ! -z "$existing_container" ]; then
+                echo "Stopping and removing existing container..."
+                docker stop $existing_container
+                docker rm $existing_container
             fi
-            sudo mv application-code/* /var/www/html
-            sudo chown -R www-data:www-data /var/www/html
-            sudo service apache2 restart
+            docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_TOKEN }}
+            docker pull ${{ secrets.DOCKERHUB_USERNAME }}/fexam:latest
+            docker run -d -p 80:80 --name my-doc-app ${{ secrets.DOCKERHUB_USERNAME }}/fexam:latest
+            docker image prune -f
